version: "3"
services:
  # docker-compose -f docker-compose.yml up --detach --build  ## for recreating th

  api:
    container_name: ${app}-api
    image: 'zelejs/allin-web:sandbox'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps
      - ./api/lib:/webapps/lib
    environment:
      TZ: "Asia/Shanghai"
      #GREENFIELD: 'run'
    privileged: true
    depends_on:
      - "mysqlserver"

  web:
    container_name: ${app}-web
    image: 'zelejs/node:sandbox'
    working_dir: /web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./web:/web
      - ./web/tmp:/web/tmp
      - ./web/logs:/web/logs
    privileged: true
    environment:
      TZ: "Asia/Shanghai"

  nginx:
    container_name: ${app}-nginx
    image: 'daocloud.io/library/nginx:latest'
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cert:/cert
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    depends_on:
      - "api"
      - "web"

  mysqlserver:
    container_name: ${app}-mysql
    image: 'daocloud.io/library/mysql:5.7'
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
    privileged: true
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    privileged: true
    volumes:
      - ./swagger/app/swagger.json:/app/swagger.json